# utils/email_generator.py (ADD THIS SECTION)

from openai import OpenAI
import os

# Assuming you have the Groq API key available (e.g., from an environment variable or imported)
groq_api_key = os.environ.get("GROQ_API_KEY", "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") 

client = OpenAI(
    api_key=groq_api_key,
    base_url="https://api.groq.com/openai/v1"
)

# utils/email_generator.py (Modified function)

def generate_email(job_details, resume_path, recruiter_name, user_name, user_email):
    # 1. Extract Details
    company_name = job_details.get("Company Name", "the Company")
    job_description = job_details.get("job description", "a specific role").strip() 
    # NOTE: Ensure 'job description' is the correct key with a space, as per your Excel headers.
    
    # 2. Determine Salutation and Subject (Generated by the LLM)
    job_title = "Data Analyst/Engineer" # Placeholder, or extract if you add a 'Job Title' column

    # 3. Construct the LLM Prompt
    # Provide the LLM with all necessary context and constraints.
    prompt = f"""
    You are an expert career consultant writing a personalized cover letter.
    
    TASK: Generate a professional cover letter suitable for email body format (no headers, footers, or subject line).
    
    GOAL: Tailor the content to show how the applicant's skills match the job requirements.
    
    APPLICANT DETAILS: 
    - Name: {user_name}
    - Field: Business Analytics, Python, SQL, Algorithms, AI, Machine Learning.

    JOB DETAILS:
    - Company: {company_name}
    - Role: {job_title}
    - Recipient (if known): {recruiter_name or 'Hiring Team'}
    - Full Job Description: {job_description}
    
    INSTRUCTIONS:
    1. Start with a professional salutation (Dear [Recruiter Name] or Dear Hiring Team).
    2. Briefly reference 1-2 key skills from the JD (e.g., Python, RDBMS) that the applicant possesses.
    3. Conclude with a strong call to action to review the attached resume.
    4. Sign off professionally with the applicant's name.
    """

    # 4. Call Groq API
    try:
        response = client.chat.completions.create(
            model="llama-3.1-8b-instant", # Use a current, high-quality Groq model
            messages=[{"role": "user", "content": prompt}],
            max_tokens=800,
            temperature=0.4 # Keep it professional, not too creative
        )
        email_body = response.choices[0].message.content.strip()
        
        # 5. Define a Standard Subject
        subject = f"Application for {job_title} Position | {user_name}"
        
        return email_body, subject

    except Exception as e:
        print(f"[Groq Email Generator] Error: {e}")
        # Fallback to a basic template if API fails
        fallback_body = f"""
Dear {recruiter_name or 'Hiring Team'},

I am writing to express my strong interest in the {job_title} position at {company_name}. My qualifications align with the job description.

Please find my tailored resume attached for your review.

Sincerely,
{user_name}
"""
        subject = f"Application for {job_title} | {user_name}"
        return fallback_body, subject